"""A Julia environment pinned to a Manifest, as a repository rule.

THE CONTRACT. The declared input is Manifest.toml. Everything about the environment
follows from it: every registered package by git tree hash, every JLL artifact by tree
hash from its Artifacts.toml, and path entries that are the consumer's own source and
therefore srcs rather than depot content. A Manifest with no git-sourced entries
therefore determines the closure, which is what makes it legitimate to treat the depot
as a keyed side effect rather than a declared output. Check your manifest for
`repo-url` entries before relying on that.

A REPOSITORY RULE, not a genrule, for two reasons. Fetch time is where hitting the
network is legitimate, and a repository rule can be made to refetch when the Manifest
changes, which is what `_watch` below is for. A build-time genrule doing the same work
would need no-sandbox plus requires-network and would be lying to Bazel about its
inputs.

WHAT IT PRODUCES. `env.sh`, a shell fragment consumers source before running julia,
and `stamp.txt`, the resolved facts (manifest sha256, Julia version, host triplet,
depot). Julia itself is not in env.sh: consumers take it as a label, the same one they
passed as `julia`, via $(location ...), so the file's content never carries a
machine-specific absolute path into an action key.

THE HOOK. Environments that resolve through a private registry or package server need
that registry in the depot BEFORE Pkg.instantiate, and fetch time is the only place
that can guarantee it. `hook` is an executable run first, with JULIA_BIN and
JULIA_DEPOT_PATH set; `hook_environ` names the variables it reads, so a change to any
of them refetches. The hook is the consumer's: this module knows nothing about any
particular registry.
"""

def _env_value(rctx, name):
    # getenv registers a dependency on the variable, so a change refetches.
    return rctx.getenv(name)

def _watch(rctx, path):
    """Registers a dependency on a file, so that changing it refetches this repository.

    rctx.path() resolves a label to a path and does NOTHING ELSE: it does not watch the
    file. Registering the dependency has to be explicit, and reading the file is how it
    is done, since watch = "auto" watches when watching that path is legal and stays
    quiet when it is not (a label pointing into another module's directory, say).

    Without this the repository stays pinned to whatever the Manifest said the first time
    it was fetched, and a changed Manifest silently reuses a depot conformed to the old
    one, which is the exact failure this module exists to prevent.

    Args:
      rctx: the repository context.
      path: the path to watch, already resolved from a label.
    """
    rctx.read(path, watch = "auto")

def _julia_depot_impl(rctx):
    # The declared input. Change the Manifest, Bazel refetches: see _watch.
    manifest = rctx.path(rctx.attr.manifest)
    _watch(rctx, manifest)
    project_dir = str(manifest.dirname)

    # Julia comes from a pinned repository (julia.toolchain, or any http_archive the
    # consumer declares), NOT from PATH. PATH made the toolchain a property of whoever
    # set the machine up, and a juliaup launcher needs $HOME, which a fetch has none of.
    julia = rctx.path(rctx.attr.julia)
    if not julia.exists:
        fail("julia_depot: {} does not exist; check the toolchain pin".format(rctx.attr.julia))

    env = {"JULIA_BIN": str(julia)}
    for name in ["JULIA_DEPOT_PATH", "JULIA_PKG_SERVER", "HOME"] + rctx.attr.hook_environ:
        value = _env_value(rctx, name)
        if value != None:
            env[name] = value

    if rctx.attr.hook != None:
        hook = rctx.path(rctx.attr.hook)
        _watch(rctx, hook)
        res = rctx.execute([str(hook)], environment = env, timeout = 600, quiet = False)
        if res.return_code != 0:
            fail("julia_depot: hook {} failed:\n{}\n{}".format(rctx.attr.hook, res.stdout, res.stderr))

    # Materialise the depot: instantiate and precompile, failing loudly if the
    # Manifest's julia_version disagrees with this Julia.
    script = rctx.path(rctx.attr._instantiate)
    _watch(rctx, script)
    res = rctx.execute(
        [str(script), project_dir, "stamp.txt"],
        environment = env,
        timeout = rctx.attr.timeout,
        quiet = False,
    )
    if res.return_code != 0:
        fail("julia_depot: instantiating {} failed:\n{}\n{}".format(project_dir, res.stdout, res.stderr))

    # env.sh is the whole consumer interface. Only the depot path is in it, and only when
    # the launching environment set one: an unset depot stays unset so Julia applies its
    # own default rather than being handed "". The path is genuinely environmental and
    # therefore the one thing that legitimately varies between machines.
    depot = env.get("JULIA_DEPOT_PATH", "")
    rctx.file("env.sh", """# Generated by julia_depot. Source before running julia.
# Julia itself is NOT here: take it as the label you passed as `julia`.
{depot_line}""".format(
        depot_line = ("export JULIA_DEPOT_PATH=" + repr(depot) + "\n") if depot else "",
    ), executable = False)

    rctx.file("BUILD.bazel", """exports_files(["env.sh", "stamp.txt"])

filegroup(
    name = "env",
    srcs = ["env.sh", "stamp.txt"],
    visibility = ["//visibility:public"],
)
""")

julia_depot = repository_rule(
    implementation = _julia_depot_impl,
    attrs = {
        "manifest": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The Manifest.toml that pins the environment. Its directory is the project.",
        ),
        "julia": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The julia binary to instantiate with, e.g. @julia_dist//:bin/julia.",
        ),
        "hook": attr.label(
            allow_single_file = True,
            doc = "Optional executable run before instantiate, with JULIA_BIN and JULIA_DEPOT_PATH set.",
        ),
        "hook_environ": attr.string_list(
            doc = "Environment variables the hook reads. Each is passed through and a change refetches.",
        ),
        "timeout": attr.int(
            default = 3600,
            doc = "Seconds. A cold instantiate of a large environment is minutes, not seconds.",
        ),
        "_instantiate": attr.label(
            default = "//julia:instantiate.sh",
            allow_single_file = True,
        ),
    },
    doc = "Instantiates and precompiles a Julia project into the ambient depot, failing loudly on a version mismatch.",
)
